package com.example.cloud.vision.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import com.google.cloud.vision.v1.ProductSearchClient;
import com.google.cloud.vision.v1.ProductSearchSettings;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

import javax.annotation.Generated;
import java.io.IOException;

@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(ProductSearchClient.class)
// Check for explicit enabling on service level (treat as false if not set),
// Or blanket module-level enabling (treat as true if not set) without explicit disabling on service level
@ConditionalOnExpression(
        "{${com.google.cloud.vision.v1.product-search.enabled:false} == true} || {${com.google.cloud.vision.v1.all-services.enabled:true} != false && ${com.google.cloud.vision.v1.product-search.enabled:true} != false}")
@EnableConfigurationProperties(ProductSearchSpringProperties.class)
public class ProductSearchSpringAutoConfiguration {
  private final ProductSearchSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(ProductSearchSpringAutoConfiguration.class);


  protected ProductSearchSpringAutoConfiguration(ProductSearchSpringProperties clientProperties,
                                                 CredentialsProvider credentialsProvider) throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from ProductSearch-specific configuration");
      }
      this.credentialsProvider =
              ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  @Bean
  @ConditionalOnMissingBean(name = "defaultProductSearchTransportChannelProvider")
  public TransportChannelProvider defaultProductSearchTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return ProductSearchSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return ProductSearchSettings.defaultTransportChannelProvider();
  }

  @Bean
  @ConditionalOnMissingBean
  public ProductSearchSettings productSearchSettings(
          @Qualifier("defaultProductSearchTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider) throws IOException {

    ProductSearchSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = ProductSearchSettings.newHttpJsonBuilder();
    } else {
      clientSettingsBuilder = ProductSearchSettings.newBuilder();
    }

    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider);

    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
              ProductSearchSettings.defaultExecutorProviderBuilder()
                      .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
                      .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
    }

    // Service-level retry logic - applying for only two methods here for simplicity
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings createProductRetrySettings =
              RetryUtil.updateRetrySettings(
                      clientSettingsBuilder.createProductSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
              .createProductSettings()
              .setRetrySettings(createProductRetrySettings);

      RetrySettings getProductRetrySettings =
              RetryUtil.updateRetrySettings(
                      clientSettingsBuilder.getProductSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
              .getProductSettings()
              .setRetrySettings(getProductRetrySettings);
    }
    // Method-level retry logic - applying for only two methods here for simplicity
    Retry createProductRetry = clientProperties.getCreateProductRetry();
    if (createProductRetry != null) {
      RetrySettings createProductRetrySettings =
              RetryUtil.updateRetrySettings(
                      clientSettingsBuilder.createProductSettings().getRetrySettings(),
                      createProductRetry);
      clientSettingsBuilder
              .createProductSettings()
              .setRetrySettings(createProductRetrySettings);
    }

    Retry getProductRetry = clientProperties.getGetProductRetry();
    if (getProductRetry != null) {
      RetrySettings getProductRetrySettings =
              RetryUtil.updateRetrySettings(
                      clientSettingsBuilder.getProductSettings().getRetrySettings(),
                      getProductRetry);
      clientSettingsBuilder
              .getProductSettings()
              .setRetrySettings(getProductRetrySettings);
    }

    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public ProductSearchClient productSearchClient(
          ProductSearchSettings productSearchSettings) throws IOException {
    return ProductSearchClient.create(productSearchSettings);
  }

}
